### ISSUE TITLE
无法正常完成系统切换

### ISSUE THREAD

**Issue by TMMXA** [losehu/uv-k5-bootloader-custom#2]
我手动刷完系统之后，在切换时进度跑到97%左右时，手台会卡死，请问这有可能是什么原因导致的呢？

**Comment by Sobollion** [comment]
> 我手动刷完系统之后，在切换时进度跑到97%左右时，手台会卡死，请问这有可能是什么原因导致的呢？

@TMMXA in my cases reason was unpacked firmware files

**Comment by TMMXA** [comment]
> > 我手动刷完系统之后，在切换时进度跑到97%左右时，手台会卡死，请问这有可能是什么原因导致的呢？
> 
> @TMMXA in my cases reason was unpacked firmware files

I didn't completely figure out the cause of this problem, but it worked after I re-burned it.
