### ISSUE TITLE
does it have to be I2C EEPROM?

### ISSUE THREAD

**Issue by ozgunawesome** [losehu/uv-k5-bootloader-custom#4]
Hello,

When upgrading the EEPROM of a standard UV-K5 do I have to use another 24 series (I2C) EEPROM as replacement or can I use SPI or Microwire instead?

I'm guessing no, due to how the board is wired, but 4 MBit I2C EEPROM is hard to find on EBay etc. the highest capacity I could find was 2 Mbit (256 KB).

I am planning to use two of these in parallel (they have one address pin routed out so I'm planning to use two of these but one with E2 low and one with E2 high - see datasheet https://www.st.com/resource/en/datasheet/m24m02-dr.pdf). Is this supported?

Thank you

**Comment by losehu** [comment]
yes,we use two 2Mbit eeprom by different E2
